apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: screensprout

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: screensprout
    includeSelectors: true
    includeTemplates: true

images:
  - name: ghcr.io/screensprout/web
    newTag: latest

replicas:
  - name: web
    count: 2
