apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: screensprout
  labels:
    app: web
    app.kubernetes.io/name: screensprout-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: screensprout
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
