apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: screensprout

resources:
  - ../../base

labels:
  - pairs:
      environment: production
    includeSelectors: false
    includeTemplates: true

patches:
  - target:
      kind: Deployment
      name: web
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web
        namespace: screensprout
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: web
                resources:
                  requests:
                    memory: "128Mi"
                    cpu: "100m"
                  limits:
                    memory: "512Mi"
                    cpu: "500m"

replicas:
  - name: web
    count: 3

images:
  - name: ghcr.io/screensprout/web
    newTag: latest
