apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: screensprout

resources:
  - website.yaml
  - routes.yaml

images:
  - name: screensprout/website
    newName: ghcr.io/screensprout/website
    newTag: latest
